version: '3.9'

services:
    db:
        image: postgres:14-alpine
#        command: postgres -c listen_addresses='*'
        restart: always
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_PASSWORD=1q2w3e4r
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
#            - ALLOW_IP_RANGE=0.0.0.0/0
    backend:
        image: moonlight234/epam_back:latest
        build:
            context: ./back
            dockerfile: Dockerfile
        restart: always
        ports: 
            - 8000:8000
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1q2w3e4r
            - DATABASE_HOST=postgres-diploma-rds.chao43ndm64b.eu-central-1.rds.amazonaws.com
            - DATABASE_PORT=5432
        depends_on:
            - db
    web:
        image: moonlight234/epam_front:latest
        build:
            context: ./front
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8080:80
        depends_on:
            - backend