version: '3.9'

services:
    db:
        image: postgres:13-alpine
#        command: postgres -c listen_addresses='*'
        restart: always
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports: 
            - 25432:5432
        environment: 
            - POSTGRES_PASSWORD=1q2w3e4r
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
#            - ALLOW_IP_RANGE=0.0.0.0/0
    backend:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        ports: 
            - 9000:8000
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1q2w3e4r
        depends_on:
            - db