deployment:
   registryBackend: "moonlight234/epam_back:"
   registryFrontend: "moonlight234/epam_front:"
   namespace: "prod"
   dbpass: "1q2w3e4r"
   # rdsendpoint: __RDSENDPOINT__
   frontTag: "latest"
   backTag: "latest"
